In [ ]:
# List cannot be manipulated directly in the way we want it
l= [2,3,4]
print(l)
print(l*2)

[2, 3, 4]
[2, 3, 4, 2, 3, 4]


In [2]:
import numpy as np
import time

In [ ]:
npa = np.array([2,3,4])
print(npa)
print(npa*2)

[2 3 4]
[4 6 8]


In [ ]:
# Manipulating with list is a tedious task
# declaring lists 
list1 = list(range(500000))  
# declaring numpy arrays 
array1 = np.arange(500000)
print(array1)

[     0      1      2 ... 499997 499998 499999]


In [ ]:
initialTime = time.time()
resultantList=[]
for i in list1:
    resultantList.append(i**2)
# calculating execution time 
print(time.time() - initialTime) 

0.19133877754211426


In [ ]:
initialTime = time.time() 
resultantArray = array1 **2 
# calculating execution time  
print(time.time() - initialTime)

0.002008199691772461


In [ ]:
# 1D Array
one = np.array([[1,2,3]])
print(one)
# print(one.ndim)
# print(type(one))
# print(one.shape)
print(one.strides) #strides are the number of bytes that should be skipped in memory to go to the next element
print(one.data) #Python buffer object pointing to the start of the array’s data.

[[1 2 3]]
(24, 8)


In [ ]:
# 2D Array
two = np.array([[1,2,3],[4,5,6]])
print(two)
print(two.ndim)
print(type(two))
print(two.shape)
print(two.strides)

[[1 2 3]
 [4 5 6]]
2
<class 'numpy.ndarray'>
(2, 3)
(24, 8)


In [ ]:
# 3D Array
print("This is how a 3D array looks like.")
print("\n")
three = np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]])
print(three)
print(three.ndim)
print(three.shape)
print(three.strides)

This is how a 3D array looks like.


[[[1 2 3]
  [3 4 5]]

 [[5 6 7]
  [7 8 9]]]
3
(2, 2, 3)
(48, 24, 8)


In [ ]:
three[0,:,:]
three[1,:,:]
three[:,0,:]
three[:,1,:]
three[:,:,0]
three[:,:,1]

In [ ]:
h_inches = [61,65,63,69,70,73,68,64,63,62]
h_np_inches = np.array(h_inches)
print(h_np_inches)
h_np_cm = h_np_inches * 2.54
h_np_m = h_np_cm / 100
print(h_np_m)

[61 65 63 69 70 73 68 64 63 62]
[1.5494 1.651  1.6002 1.7526 1.778  1.8542 1.7272 1.6256 1.6002 1.5748]


In [ ]:
w_pounds = [100,200,160,180,140,155,165,172,180,200]
w_np_pounds = np.array(w_pounds)
print(w_np_pounds)
w_np_kgs = w_np_pounds * 0.45
print(w_np_kgs)

[100 200 160 180 140 155 165 172 180 200]
[45.   90.   72.   81.   63.   69.75 74.25 77.4  81.   90.  ]


In [ ]:
# BMI
bmi = w_np_kgs / (h_np_m ** 2)
print(bmi)

[18.74499852 33.01781751 28.11797007 26.37056314 19.92861129 20.28761798
 24.889215   29.28960936 31.63271633 36.29039516]


In [ ]:
#BMI(Weight(kg)/(height(m)^2))
# Underweight = <18.5
# Normal weight = 18.5–24.9
# Overweight = 25–29.9
# Obesity = BMI of 30 or greater

In [ ]:
n = (bmi>18.5)&(bmi<25)
print(n)
bmi[n]

[ True False False False  True  True  True False False False]


array([18.74499852, 19.92861129, 20.28761798, 24.889215  ])

In [ ]:
#Subsetting arrays
x = [1,4,8,9]
y = np.array(x)
y[1]

4

In [ ]:
#Boolean method for subsetting
high = y > 5
y[high]

array([8, 9])

In [ ]:
#Slicing the array
print(y[2:4])

[8 9]


In [ ]:
#Transpose
import numpy as np
a = np.array([[2,3,4]])
print(a)
print(a.shape)
# print("\n")
a_t = a.T
print(a_t)
print(a_t.shape)

[[2 3 4]]
(1, 3)
[[2]
 [3]
 [4]]
(3, 1)


In [ ]:
#Swap axes
import numpy as np
a = np.array([[2,3,4]])
print(a)
print(a.shape)
a = np.swapaxes(a,1,0)
print(a)
print(a.shape)

[[2 3 4]]
(1, 3)
[[2]
 [3]
 [4]]
(3, 1)


In [3]:
# Arithmetic Operations
arr = np.array([2,3,4,5,6,7])
print(arr.cumsum()) #Cumulative Sum
arr.mean() #Mean
arr.std() #Standard Deviations
print(np.sqrt(arr)) #Square root
print(np.exp(arr)) # Exponential

[1.41421356 1.73205081 2.         2.23606798 2.44948974 2.64575131]
[   7.3890561    20.08553692   54.59815003  148.4131591   403.42879349
 1096.63315843]


In [4]:
#File Input and Output with Arrays
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
#Saving the array into file
np.save('xyz.npy', arr)

In [6]:
#Loading the file 
x =np.load('xyz.npy')
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
# Reshape
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
len(x)
y = x.reshape((2,2,3))
y.shape
y

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [8]:
#Ravel function for flattening of data
arr = np.arange(15).reshape((5, 3))
print("Before changing the ravelled array looking at original array")
print(arr)
rav1 = arr.ravel() #arr will change by changing of rav1
print(rav1)
rav1[0] = 1000
print(rav1)
print("After changing the ravelled array looking at original array")
print(arr)

Before changing the ravelled array looking at original array
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[1000    1    2    3    4    5    6    7    8    9   10   11   12   13
   14]
After changing the ravelled array looking at original array
[[1000    1    2]
 [   3    4    5]
 [   6    7    8]
 [   9   10   11]
 [  12   13   14]]


In [9]:
#Flatten function for flattening of data
arr = np.arange(15).reshape((5, 3))
print("Before changing the flattened array looking at original array")
print(arr)
flat1 = arr.flatten() #arr will not change by changing of flat1
print(flat1)
flat1[0] = 1000
print(flat1)
print("After changing the flattened array looking at original array")
print(arr)

Before changing the flattened array looking at original array
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[1000    1    2    3    4    5    6    7    8    9   10   11   12   13
   14]
After changing the flattened array looking at original array
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
